import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Navbar from '@/components/navbar'
import ThemeSwitch from '@/components/theme-switch'
import ThemeContextProvider from '@/context/theme-context'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/Footer'
import Providers from '@/lib/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Zil - Utak Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} dark:text-custom-8 text-custom-12`}>
        <Providers>
          <ThemeContextProvider>
            <div className='bg-custom-radial dark:bg-custom-12 fixed -z-10 h-screen w-screen duration-1000'></div>
            <Navbar />
            {children}
            <Footer />
            <ThemeSwitch />
            <Toaster position='top-center' />
          </ThemeContextProvider>
        </Providers>
      </body>
    </html>
  )
}
